image: python/3.6-alpine

before_script:
  - pip install -r requirements.txt

stages:
  - build

docker build:
  stage: build
  script:
    python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/
