image: 3.7-slim-buster  # python:3.6-alpine

#  - apk add pkgconfig gcc zeromq-dev musl-dev freetype
before_script:
  - pip install -r requirements.txt

stages:
  - build

wheel build:
  stage: build
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/jupyterthemes-0.20.0-py2.py3-none-any.whl
